[package]
name = "tubemq-client"
version = "0.1.0"
authors = ["misakachen <misakachen@tencent.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"]  }
bytes = "0.5"
